sudo : false
language : node_js
node_js :
 - stable
install :
 - npm ci
script:
 - npm run build
before_deploy:
  cd lib
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
on:
  all_branches: true
  tags: true
